apiVersion: v1
kind: Secret
metadata:
  name: airesume-secrets
  namespace: airesume
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://aniketkr2103_db_user:16sezFEXz5cJ4VWD@airesumebuilder.jlapbpa.mongodb.net/?appName=airesumebuilder"
  JWT_SECRET: "becda834ecc58993c471dd794cd8685d3ed264145d84d69bf94e8e1baed51dfaedec12f4889171a8f89ac70b6977af90ff1b912c39343afd9d2f08296ee713e3"
  GEMINI_API_KEY: "AQ.Ab8RN6Kh3YffH_KR2weHoXtuInQ2iOK7WRPtPnDraE5qRdk5uw"